spring.config.activate.on-profile=prod
spring.application.name=Practice-Springboot
server.error.include-message=always

### postgres
spring.datasource.url=${POSTGRES_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}